//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportSystemApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public string AspNetUsersId { get; set; }
        public int Id { get; set; }
        public string Message { get; set; }
        public int TicketNoID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual SupportList SupportList { get; set; }
    }
}
