//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportSystemApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportList
    {
        public int TicketNo { get; set; }
        public string Title { get; set; }
        public int Status { get; set; }
        public int Category { get; set; }
        public int Severity { get; set; }
        public int Priority { get; set; }
        public int RaisedBy { get; set; }
        public System.DateTime RaisedOn { get; set; }
        public System.DateTime DueOn { get; set; }
        public Nullable<System.DateTime> ResolvedOn { get; set; }
        public Nullable<int> IDSectionList { get; set; }
    
        public virtual CategoryList CategoryList { get; set; }
        public virtual PriorityList PriorityList { get; set; }
        public virtual SectionsList SectionsList { get; set; }
        public virtual SeverityList SeverityList { get; set; }
        public virtual StatusesList StatusesList { get; set; }
        public object AspNetUsers { get; internal set; }
    }
}
